// Generated by scripts/gen-standalone.ts — do not edit.
// Stands in for $dsh/ai outside dsh, where the harness these forward to does not exist.
export function streamText(...args) {
  console.warn("[$dsh/ai] streamText() did nothing: this page is not running inside dsh, so there is no harness to reach.", ...args);
  return (async function* () {})();
}
export default { streamText };
