// Generated by scripts/gen-standalone.ts — do not edit.
// Stands in for $dsh/chat outside dsh, where the harness these forward to does not exist.
export function sendMessage(...args) {
  console.warn("[$dsh/chat] sendMessage() did nothing: this page is not running inside dsh, so there is no harness to reach.", ...args);
}
export default { sendMessage };
