// Generated by scripts/gen-standalone.ts — do not edit.
// Stands in for $dsh/exec outside dsh, where the harness these forward to does not exist.
export function bash(...args) {
  console.warn("[$dsh/exec] bash() did nothing: this page is not running inside dsh, so there is no harness to reach.", ...args);
}
export default { bash };
