// Generated by scripts/gen-standalone.ts — do not edit.
// Stands in for $dsh/fs outside dsh, where the harness these forward to does not exist.
export async function readFile(...args) {
  console.warn("[$dsh/fs] readFile() did nothing: this page is not running inside dsh, so there is no harness to reach.", ...args);
  return "";
}
export async function readdir(...args) {
  console.warn("[$dsh/fs] readdir() did nothing: this page is not running inside dsh, so there is no harness to reach.", ...args);
  return [];
}
export async function writeFile(...args) {
  console.warn("[$dsh/fs] writeFile() did nothing: this page is not running inside dsh, so there is no harness to reach.", ...args);
}
export default { readFile, readdir, writeFile };
