// Generated by scripts/gen-standalone.ts — do not edit.
// Stands in for $dsh/web outside dsh, where the harness these forward to does not exist.
export async function search(...args) {
  console.warn("[$dsh/web] search() did nothing: this page is not running inside dsh, so there is no harness to reach.", ...args);
  return { sources: [], truncated: false };
}
export default { search };
