/**
 * Writes the `$dsh/*` standalone stubs — the import map `genui build` and `genui dev` need.
 *
 * Those two produce a page with no dsh around it, so the capabilities cannot work there: the
 * conversation, the model and the workspace all live in the harness. The stubs exist so a card
 * that imports one still *builds*, and say what happened in the console instead of throwing —
 * a half-working export beats a page that dies on the first click.
 *
 * Export names come from `bind()` rather than a second hand-written list, so a capability
 * added to the implementation cannot go missing here.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CAPABILITY_PREFIX, capabilityModule } from "../src/contract.ts";

// Imported for its shape only: `bind()` reads a host that does not exist in this process, so
// calling a member would throw — but enumerating the keys never calls one.
const { bind } = await import("../src/client/runtime/bindings.ts");

const out = resolve(import.meta.dir, "../types/standalone");
await mkdir(out, { recursive: true });

/**
 * What each stub returns, so a caller that awaits or iterates the result does not crash on
 * `undefined` — which would make the page die at the first `await readFile(...)` and defeat
 * the whole point of stubbing quietly. Keyed by member name; anything unlisted returns
 * undefined, which is right for the void-returning ones.
 */
const EMPTY_RESULT: Record<string, string> = {
  readFile: '""',
  readdir: "[]",   // DirEntry[]
  writeFile: "undefined",
  streamText: "(async function* () {})()",
};
const ASYNC = new Set(["readFile", "readdir", "writeFile"]);

const groups = bind() as Record<string, Record<string, unknown>>;
const imports: Record<string, string> = {};

for (const [group, members] of Object.entries(groups)) {
  const specifier = capabilityModule(group);
  const body = Object.keys(members).map((name) => {
    const warn = `  console.warn(${JSON.stringify(`[${specifier}] ${name}() did nothing: this page is not running inside dsh, so there is no harness to reach.`)}, ...args);`;
    const result = EMPTY_RESULT[name];
    const ret = result === undefined || result === "undefined" ? "" : `\n  return ${result};`;
    return `export ${ASYNC.has(name) ? "async " : ""}function ${name}(...args) {\n${warn}${ret}\n}`;
  });
  const source = [
    `// Generated by scripts/gen-standalone.ts — do not edit.`,
    `// Stands in for ${specifier} outside dsh, where the harness these forward to does not exist.`,
    ...body,
    `export default { ${Object.keys(members).join(", ")} };`,
    "",
  ].join("\n");
  await writeFile(resolve(out, `${group}.js`), source);
  imports[specifier] = `./${group}.js`;
}

await writeFile(resolve(out, "importmap.json"), `${JSON.stringify({ imports }, null, 2)}\n`);
console.log(`wrote ${Object.keys(imports).length} stubs for ${CAPABILITY_PREFIX}/* → types/standalone/`);
